const meals = [
  {
    idMeal: "52795",
    strMeal: "Chicken Handi",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Indian",
    strInstructions: "Take a large pot or wok, big enough to cook all the chicken, and heat the oil in it. Once the oil is hot, add sliced onion and fry them until deep golden brown. Then take them out on a plate and set aside. To the same pot, add the chopped garlic and sauté for a minute. Then add the chopped tomatoes and cook until tomatoes turn soft. This would take about 5 minutes. Then return the fried onion to the pot and stir. Add ginger paste and sauté well. Now add the cumin seeds, half of the coriander seeds and chopped green chillies. Give them a quick stir. Next goes in the spices – turmeric powder and red chilli powder. Sauté the spices well for couple of minutes. Add the chicken pieces to the wok, season it with salt to taste and cook the chicken covered on medium-low heat until the chicken is almost cooked through. This would take about 15 minutes. Slowly sautéing the chicken will enhance the flavor, so do not expedite this step by putting it on high heat. When the oil separates from the spices, add the beaten yogurt keeping the heat on lowest so that the yogurt doesn’t split. Sprinkle the remaining coriander seeds and add half of the dried fenugreek leaves. Mix well. Finally add the cream and give a final mix to combine everything well. Sprinkle the remaining kasuri methi and garam masala and serve the chicken handi hot with naan or rotis. Enjoy!",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=IO0issT0Rmc",
    strIngredient1: "Chicken",
    strIngredient2: "Onion",
    strIngredient3: "Tomatoes",
    strIngredient4: "Garlic",
    strIngredient5: "Ginger paste",
    strIngredient6: "Vegetable oil",
    strIngredient7: "Cumin seeds",
    strIngredient8: "Coriander seeds",
    strIngredient9: "Turmeric powder",
    strIngredient10: "Chilli powder",
    strIngredient11: "Green chilli",
    strIngredient12: "Yogurt",
    strIngredient13: "Cream",
    strIngredient14: "fenugreek",
    strIngredient15: "Garam masala",
    strIngredient16: "Salt",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1.2 kg",
    strMeasure2: "5 thinly sliced",
    strMeasure3: "2 finely chopped",
    strMeasure4: "8 cloves chopped",
    strMeasure5: "1 tbsp",
    strMeasure6: "¼ cup",
    strMeasure7: "2 tsp",
    strMeasure8: "3 tsp",
    strMeasure9: "1 tsp",
    strMeasure10: "1 tsp",
    strMeasure11: "2",
    strMeasure12: "1 cup",
    strMeasure13: "¾ cup",
    strMeasure14: "3 tsp Dried",
    strMeasure15: "1 tsp",
    strMeasure16: "To taste",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52956",
    strMeal: "Chicken Congee",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Chinese",
    strInstructions: "STEP 1 - MARINATING THE CHICKEN In a bowl, add chicken, salt, white pepper, ginger juice and then mix it together well. Set the chicken aside. STEP 2 - RINSE THE WHITE RICE Rinse the rice in a metal bowl or pot a couple times and then drain the water. STEP 2 - BOILING THE WHITE RICE Next add 8 cups of water and then set the stove on high heat until it is boiling. Once rice porridge starts to boil, set the stove on low heat and then stir it once every 8-10 minutes for around 20-25 minutes. After 25 minutes, this is optional but you can add a little bit more water to make rice porridge to make it less thick or to your preference. Next add the marinated chicken to the rice porridge and leave the stove on low heat for another 10 minutes. After an additional 10 minutes add the green onions, sliced ginger, 1 pinch of salt, 1 pinch of white pepper and stir for 10 seconds. Serve the rice porridge in a bowl Optional: add Coriander on top of the rice porridge.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=kqEfk801E94",
    strIngredient1: "Chicken",
    strIngredient2: "Salt",
    strIngredient3: "Pepper",
    strIngredient4: "Ginger Cordial",
    strIngredient5: "Ginger",
    strIngredient6: "Spring Onions",
    strIngredient7: "Rice",
    strIngredient8: "Water",
    strIngredient9: "Coriander",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "8 oz ",
    strMeasure2: "pinch",
    strMeasure3: "pinch",
    strMeasure4: "1 tsp ",
    strMeasure5: "1 tsp ",
    strMeasure6: "1 tbs",
    strMeasure7: "1/2 cup ",
    strMeasure8: "8 cups ",
    strMeasure9: "2 oz ",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://sueandgambo.com/pages/chicken-congee",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52831",
    strMeal: "Chicken Karaage",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Japanese",
    strInstructions: "Add the ginger, garlic, soy sauce, sake and sugar to a bowl and whisk to combine. Add the chicken, then stir to coat evenly. Cover and refrigerate for at least 1 hour. Add 1 inch of vegetable oil to a heavy bottomed pot and heat until the oil reaches 360 degrees F. Line a wire rack with 2 sheets of paper towels and get your tongs out. Put the potato starch in a bowl Add a handful of chicken to the potato starch and toss to coat each piece evenly. Fry the karaage in batches until the exterior is a medium brown and the chicken is cooked through. Transfer the fried chicken to the paper towel lined rack. If you want the karaage to stay crispy longer, you can fry the chicken a second time, until it's a darker color after it's cooled off once. Serve with lemon wedges.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=XivddFddthc",
    strIngredient1: "Chicken thigh",
    strIngredient2: "Ginger",
    strIngredient3: "Garlic",
    strIngredient4: "Soy sauce",
    strIngredient5: "Sake",
    strIngredient6: "Granulated sugar",
    strIngredient7: "Potato starch",
    strIngredient8: "Vegetable oil",
    strIngredient9: "Lemon",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "450 grams Boneless skin",
    strMeasure2: "1 tablespoon",
    strMeasure3: "1 clove",
    strMeasure4: "2 tablespoons",
    strMeasure5: "1 tablespoon",
    strMeasure6: "2 teaspoon",
    strMeasure7: "1/3 cup",
    strMeasure8: "1/3 cup",
    strMeasure9: "1/3 cup",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://norecipes.com/karaage-recipe",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52920",
    strMeal: "Chicken Marengo",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "French",
    strInstructions: "Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little. Pour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper – you shouldn’t need salt. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=U33HYUr-0Fw",
    strIngredient1: "Olive Oil",
    strIngredient2: "Mushrooms",
    strIngredient3: "Chicken Legs",
    strIngredient4: "Passata",
    strIngredient5: "Chicken Stock Cube",
    strIngredient6: "Black Olives",
    strIngredient7: "Parsley",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 tbs",
    strMeasure2: "300g",
    strMeasure3: "4",
    strMeasure4: "500g",
    strMeasure5: "1",
    strMeasure6: "100g ",
    strMeasure7: "Chopped",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/3146682/chicken-marengo",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52806",
    strMeal: "Tandoori chicken",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Indian",
    strInstructions: "Mix the lemon juice with the paprika and red onions in a large shallow dish. Slash each chicken thigh three times, then turn them in the juice and set aside for 10 mins. Mix all of the marinade ingredients together and pour over the chicken. Give everything a good mix, then cover and chill for at least 1 hr. This can be done up to a day in advance. Heat the grill. Lift the chicken pieces onto a rack over a baking tray. Brush over a little oil and grill for 8 mins on each side or until lightly charred and completely cooked through.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    strTags: "Spicy,Meat",
    strYoutube: "https://www.youtube.com/watch?v=-CKvt1KNU74",
    strIngredient1: "lemons",
    strIngredient2: "paprika",
    strIngredient3: "red onions",
    strIngredient4: "chicken thighs",
    strIngredient5: "vegetable oil",
    strIngredient6: "Greek yogurt",
    strIngredient7: "ginger",
    strIngredient8: "garlic clove",
    strIngredient9: "garam masala",
    strIngredient10: "ground cumin",
    strIngredient11: "chilli powder",
    strIngredient12: "turmeric",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 Juice",
    strMeasure2: "4 tsp",
    strMeasure3: "2 finely chopped",
    strMeasure4: "16 skinnless",
    strMeasure5: "For brushing",
    strMeasure6: "300ml ",
    strMeasure7: "large piece",
    strMeasure8: "4",
    strMeasure9: "¾ tsp",
    strMeasure10: "¾ tsp",
    strMeasure11: "½ tsp",
    strMeasure12: "¼ tsp",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "http://www.bbcgoodfood.com/recipes/1660651/tandoori-chicken",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52850",
    strMeal: "Chicken Couscous",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Moroccan",
    strInstructions: "Heat the olive oil in a large frying pan and cook the onion for 1-2 mins just until softened. Add the chicken and fry for 7-10 mins until cooked through and the onions have turned golden. Grate over the ginger, stir through the harissa to coat everything and cook for 1 min more. Tip in the apricots, chickpeas and couscous, then pour over the stock and stir once. Cover with a lid or tightly cover the pan with foil and leave for about 5 mins until the couscous has soaked up all the stock and is soft. Fluff up the couscous with a fork and scatter over the coriander to serve. Serve with extra harissa, if you like.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=GZQGy9oscVk",
    strIngredient1: "Olive Oil",
    strIngredient2: "Onion",
    strIngredient3: "Chicken Breast",
    strIngredient4: "Ginger",
    strIngredient5: "Harissa Spice",
    strIngredient6: "Dried Apricots",
    strIngredient7: "Chickpeas",
    strIngredient8: "Couscous",
    strIngredient9: "Chicken Stock",
    strIngredient10: "Coriander",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 tbsp",
    strMeasure2: "1 chopped",
    strMeasure3: "200g",
    strMeasure4: "pinch",
    strMeasure5: "2 tblsp ",
    strMeasure6: "10",
    strMeasure7: "220g",
    strMeasure8: "200g",
    strMeasure9: "200ml",
    strMeasure10: "Handful",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/13139/onepan-chicken-couscous",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52945",
    strMeal: "Kung Pao Chicken",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Chinese",
    strInstructions: "Combine the sake or rice wine, soy sauce, sesame oil and cornflour dissolved in water. Divide mixture in half. In a glass dish or bowl, combine half of the sake mixture with the chicken pieces and toss to coat. Cover dish and place in refrigerator for about 30 minutes. In a medium frying pan, combine remaining sake mixture, chillies, vinegar and sugar. Mix together and add spring onion, garlic, water chestnuts and peanuts. Heat sauce slowly over medium heat until aromatic. Meanwhile, remove chicken from marinade and sauté in a large frying pan until juices run clear. When sauce is aromatic, add sautéed chicken and let simmer together until sauce thickens.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1525872624.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=QqdcCHQlOe0",
    strIngredient1: "Sake",
    strIngredient2: "Soy Sauce",
    strIngredient3: "Sesame Seed Oil",
    strIngredient4: "Corn Flour",
    strIngredient5: "Water",
    strIngredient6: "Chicken",
    strIngredient7: "Chilli Powder",
    strIngredient8: "Rice Vinegar",
    strIngredient9: "Brown Sugar",
    strIngredient10: "Spring Onions",
    strIngredient11: "Garlic Clove",
    strIngredient12: "Water Chestnut",
    strIngredient13: "Peanuts",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 tbs",
    strMeasure2: "2 tbs",
    strMeasure3: "2 tbs",
    strMeasure4: "2 tbs",
    strMeasure5: "2 tbs",
    strMeasure6: "500g",
    strMeasure7: "1 tbs",
    strMeasure8: "1 tsp ",
    strMeasure9: "1 tbs",
    strMeasure10: "4 Chopped",
    strMeasure11: "6 cloves",
    strMeasure12: "220g",
    strMeasure13: "100g ",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "http://allrecipes.co.uk/recipe/1773/kung-pao-chicken.aspx",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  },
  {
    idMeal: "52934",
    strMeal: "Chicken Basquaise",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "French",
    strInstructions: "Preheat the oven to 180°C/Gas mark 4. Have the chicken joints ready to cook. Heat the butter and 3 tbsp olive oil in a flameproof casserole or large frying pan. Brown the chicken pieces in batches on both sides, seasoning them with salt and pepper as you go. Don't crowd the pan - fry the chicken in small batches, removing the pieces to kitchen paper as they are done. Add a little more olive oil to the casserole and fry the onions over a medium heat for 10 minutes, stirring frequently, until softened but not browned. Add the rest of the oil, then the peppers and cook for another 5 minutes. Add the chorizo, sun-dried tomatoes and garlic and cook for 2-3 minutes. Add the rice, stirring to ensure it is well coated in the oil. Stir in the tomato paste, paprika, bay leaves and chopped thyme. Pour in the stock and wine. When the liquid starts to bubble, turn the heat down to a gentle simmer. Press the rice down into the liquid if it isn't already submerged and place the chicken on top. Add the lemon wedges and olives around the chicken. Cover and cook in the oven for 50 minutes. The rice should be cooked but still have some bite, and the chicken should have juices that run clear when pierced in the thickest part with a knife. If not, cook for another 5 minutes and check again.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg",
    strTags: "Meat",
    strYoutube: "https://www.youtube.com/watch?v=emfm6TwsVhg",
    strIngredient1: "Chicken",
    strIngredient2: "Butter",
    strIngredient3: "Olive Oil",
    strIngredient4: "Red Onions",
    strIngredient5: "Red Pepper",
    strIngredient6: "Chorizo",
    strIngredient7: "Sun-Dried Tomatoes",
    strIngredient8: "Garlic",
    strIngredient9: "Basmati Rice",
    strIngredient10: "Tomato Puree",
    strIngredient11: "Paprika",
    strIngredient12: "Bay Leaves",
    strIngredient13: "Thyme",
    strIngredient14: "Chicken Stock",
    strIngredient15: "Dry White Wine",
    strIngredient16: "Lemons",
    strIngredient17: "Black Olives",
    strIngredient18: "Salt",
    strIngredient19: "Pepper",
    strIngredient20: "",
    strMeasure1: "1.5kg",
    strMeasure2: "25g",
    strMeasure3: "6 tblsp",
    strMeasure4: "2 sliced",
    strMeasure5: "3 Large",
    strMeasure6: "130g",
    strMeasure7: "8",
    strMeasure8: "6 cloves sliced",
    strMeasure9: "300g",
    strMeasure10: "drizzle",
    strMeasure11: "½ tsp",
    strMeasure12: "4",
    strMeasure13: "Handful",
    strMeasure14: "350ml",
    strMeasure15: "180g",
    strMeasure16: "2",
    strMeasure17: "100g ",
    strMeasure18: "to serve",
    strMeasure19: "to serve",
    strMeasure20: "",
    strSource: "https://www.rivercottage.net/recipes/chicken-basquaise",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null
  }
]

export default meals;